#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorAnalogInactive)
#pragma config(Sensor, S3,     IR,             sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     bucket,        tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    dumper,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    flagMount,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "hitechnic-irseeker-v2.h" //includes irseeker drivers
#include "gyro.h"//include gyro drivers
#include "pidturn.h"//includes pidturns
#include "main.h"//includes main library
#include "delay.h"//includes delay library

GYRO g_Gyro;
PIDTURN g_PidTurn;

const int MIN_TURN_POWER = 45;
const float TURN_KP = 0.85;//Default was 0.9
const float TURN_TOLERANCE = 0.3;

void initializeRobot(){
	servo[dumper] = 247;
	servo[flagMount] = 17;
	GyroInit(g_Gyro, gyro, 0);
	PidTurnInit(g_PidTurn, leftDrive, rightDrive, MIN_TURN_POWER, g_Gyro, TURN_KP, TURN_TOLERANCE);
	wait1Msec(1500);
	return;
}

task main()
{
	int timeToWait = requestTimeToWait();
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.
	//Align against right wall, with left edge of left wheels on left edge of third tile (6ft from right wall).
	countdown(timeToWait);

	moveForwardInches(50,2,false, LEFTENCODER);
	turn(g_PidTurn, 90);
	moveBackwardInches(50,15,false,LEFTENCODER);
	turn(g_PidTurn,40);

	//moveForwardInches(60, 1, false, LEFTENCODER); //away from wall
	//turn(g_PidTurn, 136); //turn to parallel with buckets
	//clearEncoders(); //clears encoder for the next step
	//moveBackwardInches(60,4, false, LEFTENCODER);


	while(HTIRS2readACDir(IR) != 5 || HTIRS2readACDir(IR) == 0){ //finds the beacon
		//nxtDisplayCenteredTextLine(1,"Direction: %d", HTIRS2readACDir(IR));
		startBackward(60);
	}

	moveBackwardInchesNoReset(60, 4);

	stopDrive();//stops robot
	servo[dumper] = 30;//dumps the block
	motor[lift]= 50;//starts the lift up
	wait1Msec(700);
	motor[lift]= 0;//stops lift
	servo[dumper] = 255;//resets servo

	wait1Msec(330);
	int ticsToMove = abs(nMotorEncoder[leftDrive]) + 90;
	moveForwardTics(90, ticsToMove, false, LEFTENCODER); //reverse back to start
	turn(g_PidTurn, 95,60); //turn backwards to go towards ramp
	moveBackwardInches(90, 38, false, LEFTENCODER); //forwards to ramp
	turn(g_PidTurn, 87, 60); //turn to face away from ramp
	moveForwardInches(90, 47, false, LEFTENCODER);//onto ramp
	while(true){}
}
