#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     bucket,        tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    dumper,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.



void initializeRobot()
{
	servo[dumper] = 110;
	return;
}


task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase

	while (true)
	{
		getJoystickSettings(joystick);
		//Drive Code
		int DriveLowerThreshold = 15;
		int DriveUpperThreshold = 75;
		if(joy1Btn(8)) DriveUpperThreshold = 100;
		int rightPower = joystick.joy1_y2;
		int leftPower = joystick.joy1_y1;
		if (abs(rightPower)> DriveUpperThreshold)
		{
			if (rightPower < 0) rightPower = DriveUpperThreshold * -1;
			else  rightPower = DriveUpperThreshold;
		}

		if(abs(leftPower) > DriveUpperThreshold)
		{
			if (leftPower < 0) leftPower = DriveUpperThreshold*-1;
			else leftPower= DriveUpperThreshold;
		}

		if(abs(rightPower) < DriveLowerThreshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
		{
			rightPower = 0;
		}
		if(abs(leftPower) < DriveLowerThreshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
		{
			leftPower = 0;
		}
		motor[rightDrive] = rightPower;
		motor[leftDrive] = leftPower;

		if(abs(joystick.joy2_y2)>30){
			if(joystick.joy2_y2 > 30){
				motor[lift] = 70;
			}
			else{
				motor[lift] = -30;
			}
		}
		else{
			motor[lift] = 0;
		}


		if(abs(joystick.joy2_y1)>30){
			if(joy2Btn(5)){
				motor[arm] = joystick.joy2_y1*70/abs(joystick.joy2_y1);
			}
			else{
				motor[arm] = joystick.joy2_y1*70/abs(joystick.joy2_y1);
			}
		}
		else{
			motor[arm] = 0;
		}

		if(joystick.joy2_TopHat == 4){
			motor[bucket] = -60;
		}
		else if(joystick.joy2_TopHat == 0){
			motor[bucket] = 60;
		}
		else{
			motor[bucket] = 0;
		}


	}
}
