#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     bucket,        tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    dumper,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

//Write code that will slowly stop the arm, instead of suddenly.
//Write code that will limit the range of the arm using the encoder.

//The rightDrive encoder is correct, but the leftDrive encoder is backwards.
//The lift encoder is backwards.
//I believe that the arm encoder is correct




void initializeRobot()
{
	servo[dumper] = 110;
	return;
}


task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase

	while (true)
	{
		getJoystickSettings(joystick);
		//Drive Code
		int DriveLowerThreshold = 15;
		int DriveUpperThreshold = 75;
		if(joy1Btn(8)) DriveUpperThreshold = 100;//if Btn 8 is pressed DriveUpperThreshold = 100???
		int rightPower = joystick.joy1_y2;
		int leftPower = joystick.joy1_y1;

		//This section controls the Drive motors
		if (abs(rightPower)> DriveUpperThreshold)//if absolute value of rightPower is greater than DriveUpperThreshold
		{
			if (rightPower < 0) rightPower = DriveUpperThreshold * -1;//if rightPower is a neg
			else  rightPower = DriveUpperThreshold;
		}

		if(abs(leftPower) > DriveUpperThreshold)
		{
			if (leftPower < 0) leftPower = DriveUpperThreshold*-1;
			else leftPower= DriveUpperThreshold;
		}

		if(abs(rightPower) < DriveLowerThreshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
		{
			rightPower = 0;
		}
		if(abs(leftPower) < DriveLowerThreshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
		{
			leftPower = 0;
		}
		motor[rightDrive] = rightPower;
		motor[leftDrive] = leftPower;

		if(abs(joystick.joy2_y2)>30){
			if(joystick.joy2_y2 > 30){
				motor[lift] = 70;
			}
			else{
				motor[lift] = -30;
			}
		}
		else{
			motor[lift] = 0;
		}

		//This section controls the arm with Btn 5
		if(abs(joystick.joy2_y1)>30){//if joystick is less than 30
			if(joy2Btn(5)){//if Btn 5 is pressed for speed boost
				motor[arm] = joystick.joy2_y1*45/abs(joystick.joy2_y1);//sets motor power to 45(changed from 30 to 40 to 45)
			}
			else{//if Btn 5 is not pressed - no speed boost
				motor[arm] = joystick.joy2_y1*20/abs(joystick.joy2_y1);//changed from 40 to 30 to 25 back to 30 to 40 30 to 20 for lower speed due to the arm falling too fast
			}
		}
		else{
			motor[arm] = 0;
		}
		//This section controls the Bucket w/ Btn 4,
		//Note:TopHat is the large circuler button with 4 arrows
		if(joystick.joy2_TopHat == 4){
			motor[bucket] = -20;//changed from 60 to 40 to 25 to 20
		}
		else if(joystick.joy2_TopHat == 0){
			motor[bucket] = 20;
		}
		else{
			motor[bucket] = 0;
		}


	}
}
