#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     bucket,        tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    dumper,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LIFT 1
#define ARM 2
#define BUCKET 3

int state = ARM;


//Constants for Screen coordinates
const int LEFT_X = 3;
const int RIGHT_X = 85;
const int BOTTOM_Y = 14;
const int TOP_Y = 60;

//Constants for button definitions
const int NO_BUTTON = -1;
const int RIGHT_BUTTON = 1;
const int LEFT_BUTTON = 2;
const int ORANGE_BUTTON = 3;
const int DARK_BUTTON = 0;





void redrawScreen(){
	if(state == LIFT){
		eraseDisplay();
		nxtDisplayCenteredBigTextLine(2,"Lift");
		nxtDisplayBigStringAt(LEFT_X, BOTTOM_Y+5, "Down");
		nxtDisplayBigStringAt(RIGHT_X-10, BOTTOM_Y+5, "Up");
	}
	else if(state == ARM){
		eraseDisplay();
		nxtDisplayCenteredBigTextLine(2,"Arm");
		nxtDisplayBigStringAt(LEFT_X, BOTTOM_Y+5, "Down");
		nxtDisplayBigStringAt(RIGHT_X-10, BOTTOM_Y+5, "Up");
	}
	else if(state == BUCKET){
		eraseDisplay();
		nxtDisplayCenteredBigTextLine(2,"Bucket");
		nxtDisplayBigStringAt(LEFT_X, BOTTOM_Y+5, "Down");
		nxtDisplayBigStringAt(RIGHT_X-10, BOTTOM_Y+5, "Up");
	}
}


task monitorOrange(){
	PlaySound(soundBeepBeep);
	PlaySound(soundFastUpwardTones);
	servo[dumper] = 110;
	while(true){

		if(nNxtButtonPressed == ORANGE_BUTTON){

			while(nNxtButtonPressed == ORANGE_BUTTON){}
			if(state == ARM){
				state = LIFT;
				redrawScreen();
			}
			else if(state == LIFT){
				while(nNxtButtonPressed == ORANGE_BUTTON){}
				state = BUCKET;
				redrawScreen();
			}
			else if(state == BUCKET){
				//while(nNxtButtonPressed == ORANGE_BUTTON){}
				state = ARM;
				redrawScreen();
			}
		}
	}
}






task main() {
	redrawScreen();
	StartTask(monitorOrange);
	while(true){
		if(nNxtButtonPressed == NO_BUTTON){
			motor[lift] = 0;
			motor[arm] = 0;
			motor[bucket] = 0;
		}
		if(state == LIFT){
			if(nNxtButtonPressed == LEFT_BUTTON){
				motor[lift] = -30;
			}
			else if(nNxtButtonPressed == RIGHT_BUTTON){
				motor[lift] = 70;
			}
		}
		else if(state == ARM){
			if(nNxtButtonPressed == LEFT_BUTTON){
				motor[arm] = -70;
			}
			else if(nNxtButtonPressed == RIGHT_BUTTON){
				motor[arm] = 70;
			}
		}
		else if(state == BUCKET){
			if(nNxtButtonPressed == LEFT_BUTTON){
				motor[bucket] = -30;
			}
			else if(nNxtButtonPressed == RIGHT_BUTTON){
				motor[bucket] = 30;
			}
		}

	}//end of while(true)



}	//End of main()
